### ISSUE TITLE
Makefile: ncurses5-config not available

### ISSUE THREAD

**Issue by ghost** [di-br/ScoobyCAN#1]
First off, I never did ncurses apps, so not sure about this.
I am using Arch Linux, rather bleeding-edge distro. Command `ncurses5-config` is not available in any official Arch package. Replacing with `ncursesw6-config` worked for me. Perhaps more generic is standard `pkg-config` ? Output is the same for both, compilation and apps now working fine.
My current Makefile diff:
```
-CFLAGS  += `ncurses5-config --cflags`
-LDFLAGS += `ncurses5-config --libs`
+CFLAGS  += `pkg-config --cflags ncurses`
+LDFLAGS += `pkg-config --libs ncurses`
```

**Comment by di-br** [comment]
I don't know much about ncurses either, as I'm sure is obvious from the code. I started from the original repo and could achieve what I was aiming for quickly.
The output from `pkg-config` (which I keep forgetting about) is slightly different for me (on a Debian), but it does compile and run. So all seems fine and appears to be more version agnostic, thanks for the suggestion.
