### ISSUE TITLE
duplicate CAN frames in examples/candump.log

### ISSUE THREAD

**Issue by ghost** [di-br/ScoobyCAN#2]
Looks like almost all frames in `examples/candump.log` are duplicate. How come?
```
cat examples/candump.log | wc -l
131342
uniq examples/candump.log | wc -l
65677
```

Quick solution - without modifying file:
`canplayer -v vcan0=slcan0 < examples/candump.log | uniq `

**Comment by di-br** [comment]
Interesting. I have obviously not looked at the (raw) file closely. My first reaction was that it's a direct dump from the CAN bus and that many frames will only differ in their time stamp. But they obviously don't. Not all my dumps seem to have this (most are fine), so I guess I used a wrong flag with `candump` in this case.

I'll fix the file, thanks!
